### ISSUE TITLE
[Bug] The launcher does not manage to launch the game on Ubuntu

### ISSUE THREAD

**Issue by BettaSplendid** [qrrk/Catapult#11]
**# Summary of the issue**
After installing the launcher using the catapult-linux-x64-21.09f file, i installed the game with the big bold button, then tried to launch, but nothing happened.

I tried to use an earlier stable, as well as one experimental, but nothing happens when i press the button.I do not get an error either. I did try to turn on debug mode to see if that would change anything, but no.

**# Some info :**
I am running Ubuntu 20.04.2 LTS 2 on a modern laptop.

![image](https://user-images.githubusercontent.com/93126461/139436012-dabda01b-f80b-4634-a897-8f82e2add183.png)

**Comment by qrrk** [comment]
1. Did the game install properly? I.e. are there game files in `dda/current`?
2. Does the game start on its own, without the launcher, if you just run the `cataclysm-launcher` script?

**Comment by lbnesquik** [comment]
I will answer you once i get back to my machine. I don't have access over the weekend.

**Comment by BettaSplendid** [comment]
Right so, i tried to reinstall the game using your launcher, and this time, it worked! 
 
But then i remembered having installed it from something i got off the official git/website, so i went ahead and deleted your launcher folder, deleted packages and stuff from the command line and re-installed it again. 

And this time, it didn't work. So i am a little confused about what's happening. Maybe your launcher can't find the correct files? 

---

As for running the cataclysm-launcher thing, when i double click it, it opens in Emacs. And i have no idea how to run that. Sorry.

**Comment by BettaSplendid** [comment]
Okay, i have some more info by recreating the process that got me there.
What i did was use the command `sudo apt install cataclysm-dda-curses cataclysm-dda-sdl` from this link https://github.com/CleverRaven/Cataclysm-DDA, in the READ ME, for the UBUNTU downloads section.

After using it and letting it do its thing, i installed your launcher, installed the latest version and i could launch from your launcher. 

A fun difference is that your launcher gives me the french version first, but the command installed launch gives me english, and it seems to have kept a created world and units settings. Maybe i haven't managed to clear ALL of the remaining data. 

I hope this help.

**Comment by qrrk** [comment]
This tells me that some libraries required by Cataclysm were missing from your system. I know about a similar problem on Arch (#3) and even had it myself in the past. This is odd, because they should all be pre-installed on Ubuntu, and I didn't run into this problem when testing Catapult there.

When you installed the game from Ubuntu's repository, it pulled all necessary dependencies. When you were purging everything, you may have also used `apt autoremove`, which would have uninstalled them again.

Most likely it's `libSDL2` that was missing, but perhaps something else, too. If you ever encounter this problem again, you can run `ldd cataclysm-tiles` in the game directory to see what libraries Cataclysm requires to run and where they are on your system. If it says "not found" next to any of them, look up what package provides that library on your distro and install it.

**Comment by BettaSplendid** [comment]
```
stagiaire10@stagiaire10-HP-ProBook-650-G4:~/Téléchargements/CDDA/dda/current$ ldd cataclysm-tiles
	linux-vdso.so.1 (0x00007ffd85bc9000)
	libSDL2_mixer-2.0.so.0 => /lib/x86_64-linux-gnu/libSDL2_mixer-2.0.so.0 (0x00007fd215e45000)
	libSDL2-2.0.so.0 => /lib/x86_64-linux-gnu/libSDL2-2.0.so.0 (0x00007fd215cf0000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fd215ccd000)
	libSDL2_ttf-2.0.so.0 => /lib/x86_64-linux-gnu/libSDL2_ttf-2.0.so.0 (0x00007fd215cc4000)
	libSDL2_image-2.0.so.0 => /lib/x86_64-linux-gnu/libSDL2_image-2.0.so.0 (0x00007fd215ca1000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fd215abf000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fd21596e000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fd215953000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fd215761000)
	libmodplug.so.1 => /lib/x86_64-linux-gnu/libmodplug.so.1 (0x00007fd2155d6000)
	libfluidsynth.so.2 => /lib/x86_64-linux-gnu/libfluidsynth.so.2 (0x00007fd215504000)
	libvorbisfile.so.3 => /lib/x86_64-linux-gnu/libvorbisfile.so.3 (0x00007fd2154f9000)
	libFLAC.so.8 => /lib/x86_64-linux-gnu/libFLAC.so.8 (0x00007fd2154b9000)
	libmpg123.so.0 => /lib/x86_64-linux-gnu/libmpg123.so.0 (0x00007fd215459000)
	libopusfile.so.0 => /lib/libopusfile.so.0 (0x00007fd21524d000)
	libasound.so.2 => /lib/x86_64-linux-gnu/libasound.so.2 (0x00007fd215152000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fd21514c000)
	libpulse.so.0 => /lib/x86_64-linux-gnu/libpulse.so.0 (0x00007fd2150f7000)
	libX11.so.6 => /lib/x86_64-linux-gnu/libX11.so.6 (0x00007fd214fb8000)
	libXext.so.6 => /lib/x86_64-linux-gnu/libXext.so.6 (0x00007fd214fa3000)
	libXcursor.so.1 => /lib/x86_64-linux-gnu/libXcursor.so.1 (0x00007fd214f96000)
	libXinerama.so.1 => /lib/x86_64-linux-gnu/libXinerama.so.1 (0x00007fd214f91000)
	libXi.so.6 => /lib/x86_64-linux-gnu/libXi.so.6 (0x00007fd214f7f000)
	libXrandr.so.2 => /lib/x86_64-linux-gnu/libXrandr.so.2 (0x00007fd214f72000)
	libXss.so.1 => /lib/x86_64-linux-gnu/libXss.so.1 (0x00007fd214f6b000)
	libXxf86vm.so.1 => /lib/x86_64-linux-gnu/libXxf86vm.so.1 (0x00007fd214f64000)
	libwayland-egl.so.1 => /lib/x86_64-linux-gnu/libwayland-egl.so.1 (0x00007fd214f5f000)
	libwayland-client.so.0 => /lib/x86_64-linux-gnu/libwayland-client.so.0 (0x00007fd214f4e000)
	libwayland-cursor.so.0 => /lib/x86_64-linux-gnu/libwayland-cursor.so.0 (0x00007fd214f43000)
	libxkbcommon.so.0 => /lib/x86_64-linux-gnu/libxkbcommon.so.0 (0x00007fd214f01000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fd215e86000)
	libfreetype.so.6 => /lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007fd214e40000)
	libpng16.so.16 => /lib/x86_64-linux-gnu/libpng16.so.16 (0x00007fd214e08000)
	libjpeg.so.8 => /lib/x86_64-linux-gnu/libjpeg.so.8 (0x00007fd214d83000)
	libtiff.so.5 => /lib/x86_64-linux-gnu/libtiff.so.5 (0x00007fd214d02000)
	libwebp.so.6 => /lib/x86_64-linux-gnu/libwebp.so.6 (0x00007fd214c98000)
	libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007fd214b6d000)
	libgmodule-2.0.so.0 => /lib/x86_64-linux-gnu/libgmodule-2.0.so.0 (0x00007fd214b67000)
	libjack.so.0 => /lib/x86_64-linux-gnu/libjack.so.0 (0x00007fd214b1b000)
	libpulse-simple.so.0 => /lib/x86_64-linux-gnu/libpulse-simple.so.0 (0x00007fd214b14000)
	libsndfile.so.1 => /lib/x86_64-linux-gnu/libsndfile.so.1 (0x00007fd214a96000)
	libdbus-1.so.3 => /lib/x86_64-linux-gnu/libdbus-1.so.3 (0x00007fd214a45000)
	libreadline.so.8 => /lib/x86_64-linux-gnu/libreadline.so.8 (0x00007fd2149f3000)
	libinstpatch-1.0.so.2 => /lib/x86_64-linux-gnu/libinstpatch-1.0.so.2 (0x00007fd214938000)
	libgobject-2.0.so.0 => /lib/x86_64-linux-gnu/libgobject-2.0.so.0 (0x00007fd2148d8000)
	libvorbis.so.0 => /lib/x86_64-linux-gnu/libvorbis.so.0 (0x00007fd2148aa000)
	libogg.so.0 => /lib/x86_64-linux-gnu/libogg.so.0 (0x00007fd21489d000)
	libopus.so.0 => /lib/x86_64-linux-gnu/libopus.so.0 (0x00007fd21483c000)
	libpulsecommon-13.99.so => /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-13.99.so (0x00007fd2147ba000)
	libxcb.so.1 => /lib/x86_64-linux-gnu/libxcb.so.1 (0x00007fd214790000)
	libXrender.so.1 => /lib/x86_64-linux-gnu/libXrender.so.1 (0x00007fd214586000)
	libXfixes.so.3 => /lib/x86_64-linux-gnu/libXfixes.so.3 (0x00007fd21457e000)
	libffi.so.7 => /lib/x86_64-linux-gnu/libffi.so.7 (0x00007fd214570000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fd214554000)
	libzstd.so.1 => /lib/x86_64-linux-gnu/libzstd.so.1 (0x00007fd2144ab000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007fd214482000)
	libjbig.so.0 => /lib/x86_64-linux-gnu/libjbig.so.0 (0x00007fd214274000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007fd2141ff000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fd2141f4000)
	libvorbisenc.so.2 => /lib/x86_64-linux-gnu/libvorbisenc.so.2 (0x00007fd214149000)
	libsystemd.so.0 => /lib/x86_64-linux-gnu/libsystemd.so.0 (0x00007fd21409a000)
	libtinfo.so.6 => /lib/x86_64-linux-gnu/libtinfo.so.6 (0x00007fd21406a000)
	libwrap.so.0 => /lib/x86_64-linux-gnu/libwrap.so.0 (0x00007fd21405c000)
	libasyncns.so.0 => /lib/x86_64-linux-gnu/libasyncns.so.0 (0x00007fd213e56000)
	libapparmor.so.1 => /lib/x86_64-linux-gnu/libapparmor.so.1 (0x00007fd213e41000)
	libXau.so.6 => /lib/x86_64-linux-gnu/libXau.so.6 (0x00007fd213e3b000)
	libXdmcp.so.6 => /lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007fd213e33000)
	liblz4.so.1 => /lib/x86_64-linux-gnu/liblz4.so.1 (0x00007fd213e10000)
	libgcrypt.so.20 => /lib/x86_64-linux-gnu/libgcrypt.so.20 (0x00007fd213cf2000)
	libnsl.so.1 => /lib/x86_64-linux-gnu/libnsl.so.1 (0x00007fd213cd5000)
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007fd213cb9000)
	libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007fd213c9f000)
	libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007fd213c7a000)

```


---

In case you wanted the output of running it in the folder :: 

![image](https://user-images.githubusercontent.com/93126461/140502631-7fee179c-c86f-4cca-99db-ba20fa2f18dc.png)


Any of the ones above didn't work, but i think that's normal.

I think we are good then?

**Comment by qrrk** [comment]
Yes. I'll keep this in mind if I ever write any FAQ or troubleshooting guide.
