### ISSUE TITLE
Wrong Russian language icon

### ISSUE THREAD

**Issue by nikitazoshchuk** [qrrk/Catapult#115]
In launcher in the settings tab icon for Russian language is wrong ( https://github.com/qrrk/Catapult/blob/master/icons/lang/lang_ru.svg )
Instead of Russian flag launcher uses flag of terroristic organization FRL.
This might get people who play in Russian in trouble if they stream the game and open settings tab. This can get people fined or sent to jail.
Please use the correct flag.

**Comment by VladicusMagnus** [comment]
>  Please use the correct flag.
Никита, давайте вы не будете строить из себя дурака, и рассказывать про то, что флаг там террористов или нет. В первую очередь, в нормальной стране, террористическим флагом как раз таки посчитают "correct flag", а не бело-сине-белый. 
В общем, просьба, прекращать делать вид, что вы умственно-неполноценный.

**Comment by Zireael07** [comment]
As someone who's not Russian and who only knows a bit: No, FRL is not a terrorist organization. But I believe the launcher should use the official flag of Russia, because Russian as a language is used outside of Russia too, and most people outside of Russia won't recognize the blue-white-blue flag

**Comment by nikitazoshchuk** [comment]
> > В первую очередь, в нормальной стране, террористическим флагом как раз таки посчитают "correct flag", а не бело-сине-белый.

Под "нормальной" страной вы имеете ввиду нацистскую украину или её хозяев американцев?

**Comment by VladicusMagnus** [comment]
> As someone who's not Russian and who only knows a bit: No, FRL is not a terrorist organization. But I believe the launcher should use the official flag of Russia, because Russian as a language is used outside of Russia too, and most people outside of Russia won't recognize the blue-white-blue flag

Hmm... And the choice is not by the flag, but by the name of the language (Russian). Is this option missing? And why, then, is the Russian language needed if this person cannot read the name of this language?

**Comment by VladicusMagnus** [comment]
> Под "нормальной" страной вы имеете ввиду нацистскую украину или её хозяев американцев?
Да-да. Сразу видно, где на самом деле, нацизм. Вы даже не представляете, насколько нацистская ваша фраза. И эти люди, еще что то говорят про нацизм в Украине. Угу. Шизофрения и деперсонализация, как есть. 

К слову, я беларус. И ничего нацистского вот в Украине не вижу. Зато очень много вижу нацизма в России. Начиная от прыгания "Кто не прыгает тот хач" (задолго до "Москоляку на гiляку") и прочего. Еще сначала 2000ых годов. 

Так что, давайте ка вы перестанете пытаться продавить свои хотелки. Радуйтесь, что русский язык вообще есть. Многие нормальные компании убирают русскую локализацию, за всё хорошее. Подумайте, может это проблема с Россией, что почти ВСЕ страны считают её токсической страной? Ну, даже мысль в голову не залетает, что может это раша виновата с россиянами, а не весь мир?

**Comment by Zireael07** [comment]
@VladicusMagnus I'm not a Russian speaker but I can read a bit (you from Belarus?) and I only play in default, so I don't know what the language selection looks like. If you say it's only by name, then I propose a compromise solution: don't display any flag for Russian at all.

**Comment by VladicusMagnus** [comment]
@Zireael07 The solution is indeed a compromise. But, let's ask ourselves a question. Why did the author try and make exactly such an icon as it is? He had some idea that he wanted to convey to the Russians (and Russian speakers).

PS. And yes, you're right, I'm from Belarus.

**Comment by nikitazoshchuk** [comment]
> К слову, я беларус. И ничего нацистского вот в Украине не вижу. Зато очень много вижу нацизма в России. 

Тогда можете начать разговаривать на украинском и носить эмблемы азова, раз вам так промыл мозги коллективный запад. 
Мне с вами больше не о чем разговаривать, Влад Качерский.
