### ISSUE TITLE
Improvements & Fixes

### ISSUE THREAD

**Issue by VladicusMagnus** [qrrk/Catapult#116]
**1.** The program does not detect very well (does not detect at all) a broken connection. Thus, a broken connection leads to unexpected actions. The absence of the "Cancel" button (when downloading) does not make life easier and stable.

Suggestion: 
a. add "Cancel" button on refresh. 
b. add a connection failure check and prevent actions when the Internet connection is lost.

**2.** There is a need to leave the old versions CDDA.

Suggestion: 
Do not delete the zip archive after unpacking. In Settings, add the choice of the directory where the archive will be copied or initially loaded. Also, add an option to allow or disable such an action. By default, this option is turned off (I, or those who need it, will turn it on themselves).

**3.** If there are several versions of the game, it is not possible to determine which directory contains the desired game.

Suggestion: 
Indicate in the name of the directory, the version of the game and assembly. In the form of a "crutch" you can create a text file with the build version of the game, and the download date(bad, but...).

P.S. A joke with a click on the I icon, is quite funny. I appreciated it. But, nevertheless, it is better to leave contact data in more accessible places.

**Comment by qrrk** [comment]
These are 3 unrelated problems, so can you please create separate issues for them?

**Comment by VladicusMagnus** [comment]
No problem. I, on the contrary, did not want to "litter up" with topics of issues.
