### ISSUE TITLE
[Suggestion] Add some notes to the readme.md file for linux users

### ISSUE THREAD

**Issue by BettaSplendid** [qrrk/Catapult#12]
Hello, i just want to suggest that you put some tips for linux users installation.
I did not manage to run the launcher until i went into properties and allowed the file to run as an executable. 

![image](https://user-images.githubusercontent.com/93126461/139436618-826b3da9-08b5-4ca5-b577-60ab084355f7.png)

Have a great day and thanks for coding this tool.

**Comment by qrrk** [comment]
Good idea, thanks!
