### ISSUE TITLE
Cannot extract downloaded zip on Windows

### ISSUE THREAD

**Issue by scarf005** [qrrk/Catapult#120]
![image](https://github.com/qrrk/Catapult/assets/54838975/532adba2-e378-4223-b6b7-debf3888bb7c)

[original report from BN discord](https://discord.com/channels/830879262763909202/1093580823351001098/1132444952513753149)

Path names look ok, so not sure what is the primary cause.

**Comment by qrrk** [comment]
This looks like it should work; not sure what the problem is here. Try putting the launcher in its own dedicated folder and make sure you have full permissions in it. Keeping everything spilled out in downloads is not the best idea anyway.

**Comment by VladicusMagnus** [comment]
@scarf005 , Most likely that unzip did not work. And here's why ... Have you checked the option with the antivirus turned off? Administrator rights - I do not even mention.

**Comment by VladicusMagnus** [comment]
@qrrk By the way. The program does not check the percentage of the archive downloaded, and switches to the next algorithm. Of course, there will be an error. But I already said it.

**Comment by NobleJake** [comment]
@VladicusMagnus Yes, I've turned off the firewall as well, and I'm running as administrator, but I still get that message.

**Comment by VladicusMagnus** [comment]
@NobleJake Try a test like this. Run the uznip.exe downloaded from [here](https://github.com/qrrk/Catapult/tree/master/utils) on the command line. Would it work? At the moment it is not entirely clear at what stage you have an error. When downloading, when running unzip.exe, or when unzipping an archive.

**Comment by VladicusMagnus** [comment]
@NobleJake Try a test like this. Run the uznip.exe downloaded from [here](https://github.com/qrrk/Catapult/tree/master/utils) on the command line. Would it work? At the moment it is not entirely clear at what stage you have an error. When downloading, when running unzip.exe, or when unzipping an archive.

**Comment by NobleJake** [comment]
@VladicusMagnus As it turns out, I was still using the catapult that I downloaded last April, and that's why I was getting this error.. XD

**Comment by scarf005** [comment]
Closing as the issue seems to be fixed on latest releases.
