### ISSUE TITLE
Add latest stable version (0.3) of Cataclysm: Bright Nights

### ISSUE THREAD

**Issue by jeremy-miller** [qrrk/Catapult#124]
Version [0.3](https://github.com/cataclysmbnteam/Cataclysm-BN/releases/tag/cbn-0.3) of Cataclysm: Bright Nights was released recently. Please add it to the list of available builds for the "Stable" channel.

**Comment by Brensom** [comment]
0.4 is the latest
https://github.com/cataclysmbnteam/Cataclysm-BN/releases/tag/cbn-0.4

**Comment by yay855** [comment]
Seriously, Bright Nights has had two stable versions that aren't on Catapult's BN stables list.
