### ISSUE TITLE
Change the icon of the Russian flag to the Soviet one

### ISSUE THREAD

**Issue by RikCost** [qrrk/Catapult#135]
FRL is not associated with (the idea of ​​a "free") Russia and I, as a player, am not very pleased to see such a flag. Is it possible to replace it with a more pleasant one for Russian-speaking users, the Soviet one, maybe?

**Comment by VladicusMagnus** [comment]
@RikCost Та плин. Вы совсем уже того? Что у вас, шовинистов "великорусских" свербит то? Еще и на советский поменять предлагаете...

**Comment by RikCost** [comment]
I just don't like FRL.

**Comment by RikCost** [comment]
> @RikCost Та плин. Вы совсем уже того? Что у вас, шовинистов "великорусских" свербит то? Еще и на советский поменять предлагаете...

I just don't like FRL. In my opinion, it will not be possible to “liberate” Russia with the help of weapons.

**Comment by VladicusMagnus** [comment]
@RikCost Ну ладно. Не будем разводить особо политоту, и соглашусь с мнением. Плюрализм мнений, всё такое. Итого, есть три варианта. Обычный российский флаг, который ныне токсичен, советский, который не менее токсичен и более идиотичен. Насколько я могу судить, в СССР вы не жили, и понятия не имеете что это такое и почему советский флаг в разы даже хуже российского триколора. Если не в порядки хуже. И есть обычный флаг который особо ничем себя не запятнал. В отличии от красной тряпки и триколора. Как бы очевидный выбор, нет? Два дискредитированных символа, и один без особого бэкграунда. То что ВЫ считаете что стоит за этим флагом, это все так, разговоры в пользу бедных. На данный момент, на данном флаге нет тех преступлений которые стоят за альтернативами. Вариант четыре - вы можете создать новый флаг, но как мне кажется, у вас это не выйдет. В итоге, просто исходя из принципа рациональности, логичности и прагматизма, оставить данный флаг который сейчас есть, это наиболее нормальный результат. 
К слову, я бы достаточно аккуратно подходил к таким вопросам. Так как уже пару раз видел, что за слишком сильное педалирование тем с русским языком и символами, разработчики просто удаляли русский язык в принципе, что бы не получать (вы третий кто с этим вопросом пришел сюда) вот такие вот головные боли на ровном месте. Вам тогда люди скажут очень много "теплых и ласковых" слов. Может даже и не унесёте. Оно вам надо?

**Comment by RikCost** [comment]
@VladicusMagnus But I don’t want to accept as my own a flag created by ancient people. In my opinion, it looks like the USA flag was replaced with the Confederate flag, but this flag has more connection with the Americans than the FRL with Russian speakers.

**Comment by VladicusMagnus** [comment]
@RikCost Относитесь к этому проще. Магическое мышление не очень хорошо смотрится у современного человека. Флаг, это просто разноцветная тряпка, которой обозначали себя от других, что бы не перепутать. Сейчас же, флагам, и гербу, прямо мистическое значение предъявляют. Хотя как был тряпкой, так и остался тряпкой. С гимном, к слову, та же история. 
И нет, флаг ПРБ это "свежее", древние люди тут точно не при чем . К слову, не то что бы я считаю мечтателей о ПРБ нормальными людьми. Ну так.

**Comment by RikCost** [comment]
My mistake, I chose the wrong word, I meant outsiders and not ancient. I don't care about ancient ancestors.

**Comment by VladicusMagnus** [comment]
It would be smarter to write in Russian. If you are Russian speaking.
And even more so. It doesn’t matter what flag there is then. Just don't pay any attention.

**Comment by Tranberry** [comment]
Smarter so that other will have a harder time to follow?

@qrrk I'd love to hear your stance on that.

**Comment by VladicusMagnus** [comment]
@Tranberry Well... Including. )))
This flag hate is boring. I think you understand what i mean.

**Comment by KawaiiSelbst** [comment]
Then why add flags at all? Let's remove them all. Or still let the flags be authentic, the tricolor is still the official state symbol, and is associated with Russia more than the white and blue rag, which I have mostly associated with some Finland, and to Russia in principle has nothing to do. If there is such a flag here, with the purpose of separating the Russian language from Russia, because indeed Russian is spoken by many countries, then it's also a mistake, this banner has no connection to russian lang. 

Even the [repository](https://github.com/starship/starship), whose contributors are full of nutters who don't even consider Russian citizens as people , have the Russian flag in the readme to switch to the readme in Russian. And re-labeling labels is kindergarten

**Comment by VladicusMagnus** [comment]
@KawaiiSelbst 
Bro, where do you live?
I am in Belarus. What the russians are doing is enough for me.

Так то кавай )))

**Comment by Malihor** [comment]
Искажение флага другой страны является простым оскорблением по национальному признаку, нет в этом ни какого проявления взглядов, простое желание оскорбить. У поставившего такую картинку флага или какая то раздутая личная обида которую он проецирует на целую нацию или фанатичные радикальные взгляды. Ну или просто проблемы с головой в следствии пропаганды.

**Comment by VladicusMagnus** [comment]
@Malihor Национальному? Ты обо что ударился ))) Али вашу же конституцию не читал? Рашка - МНОГОНАЦИОНАЛЬНАЯ страна. Так по какому же национальному признаку он собирается оскорбить? Откуда вас таких 11 рублёвых набирают, из каких болот вы выползаете, не умеющие даже в логику, не говоря уже про знания основных документов СВОЕЙ же страны. Ладно бы другой, но так своей же не знаешь. 

И нет. С головой и пропагандой у тебя, проблема, резинотехническое изделие №2 пользованно-штопанное.

**Comment by Malihor** [comment]
@VladicusMagnus Что ни слово в ваших тестах то попытка язвить, обзывать, о вежливости и рамках приличия ничего не слышали?

**Comment by VladicusMagnus** [comment]
@Malihor А, простите, как еще, с "вяликарусскем" шовинистом обращаться? Только как на территории Украины, через прорезь прицела. 
Так что вам еще очень везет.

**Comment by Tranberry** [comment]
Jag anser att det är helt okej att markera mot landet som fortsätter att kämpa för något som ingen utanför Björnlandet ser något positivt med. Vi slösar massvis av våra pengar på att markera att vi inte tänker 'Åh, du är lite stark, då kan du göra vad du vill', vilket är rätt, och det försvarar verkligen den vrede som yttrar sig när man byter ut flaggan för språket.

För övrigt anser jag att alla översättningar förutom engelska bör tas bort.

**Comment by RikCost** [comment]
@VladicusMagnus  Malihor means state nationalism, not ethnic

**Comment by KawaiiSelbst** [comment]
> @KawaiiSelbst Bro, where do you live? I am in Belarus. What the russians are doing is enough for me.
> 
> Так то кавай )))

Из России бро

**Comment by mikegogulski** [comment]
Wow, what an INCREDIBLE thread! Hey, do any of y'all smoke weed?

**Comment by AriaMoradi** [comment]
This repo is not a place for political discussions, PRs for changing the flag to the current official Russian flag are welcome.

**Comment by Kutosss** [comment]
![Image](https://github.com/user-attachments/assets/ce4d44e1-2d0e-41d6-9ab4-98ef6aea8060)
