### ISSUE TITLE
Savegame backups should be zip files

### ISSUE THREAD

**Issue by benway7000** [qrrk/Catapult#136]
The save_backups folder quickly gets an enormous number of files which causes slowdown for File Explorer and I was also concerned about SyncThing having to deal with so many files.

The worlds could be zipped up instead of copied to greatly reduce the number of files in the backup.

**Comment by VladicusMagnus** [comment]
Great idea. Although it is far from new.

**Comment by AriaMoradi** [comment]
Completed in #148
