### ISSUE TITLE
Stable releases

### ISSUE THREAD

**Issue by BlazingImp77151** [qrrk/Catapult#139]
Is there a way to automatically update the launcher to show new stable branches as well?
That and updating the launcher, I had to manually install a new version because the one I had installed only went to Bright Nights 0.2 rather than all the way to 0.4

**Comment by VladicusMagnus** [comment]
@BlazingImp77151 This is a serious problem with this launcher. He seldom sees new builds. The only way to save yourself is by checking yourself every day. Which is stupid.
Sorry for bad English.

**Comment by BlazingImp77151** [comment]
Nah, your English was fine. On par if not better than what I could say, and I'm a native English speaker.

As for your point, it really seems that way. Seems like the best bet is to just download them yourself. I'm still gonna have Catapult, but I've been manually going through the files for stuff. I wonder if one of the other launchers (or the other launcher?) is any better.

**Comment by VladicusMagnus** [comment]
))) Thanks, but i rate my knowledge very well. My eng skills are terrible and there is no chance of changing the situation(to best 
 or bed... Hmm... Joke :) ). ))))

This launcher is not bad. It has many shortcomings, but I didn’t notice any critical ones. Although the author's slight apathy can actually be a serious drawback. Well, you can’t forget about a project that people use. We're not corporations.

**Comment by AriaMoradi** [comment]
Tracking progress in #150
