### ISSUE TITLE
Неверная иконка флага русского языка.

### ISSUE THREAD

**Issue by Malihor** [qrrk/Catapult#143]
Флаг России в строке выбора языка искажен. Данное действие автора не является каким то идейным заявлением а простое оскорбление по национальному признаку. Предлагаю автору не быть обиженкой и не разжигать ненависть национальному признаку.

**Comment by VladicusMagnus** [comment]
@Malihor Пожалуйся майору, иудушка. И почему не на войне, не в окопах? А на, скажем так, информационном фронте, "рискуем жизнью"?  За денюжку малую, али от рождения на головушку скорбный?

**Comment by Malihor** [comment]
@VladicusMagnus  Сколько агрессии и ненависти, не поленился напечатать простыню текста, видимо жизнь серьёзно обидела? Мое предположение что за пределами интернета жизни у вас нет.
Не имеет значение сколько желчи бурлит в подобных деятелях, оскорбление есть оскорбление, будьте людьми а не сгустками нечистот.

**Comment by VladicusMagnus** [comment]
@Malihor Повторюсь. Выучите хотя бы в пределах средней школы русский язык. Свалите из Украины. Выплатите репарации... И вот только потом, вы, русня, будете иметь право на претензии. Террорист прав не имеет. А россия - это террористическое образование (не страна уже). А вы, пособник террористов. Минимум. 

Так что ваши попытки меня зацепить - смешны.  Мнение украинского чернозёма - для меня имеет нулевую ценность.

**Comment by 97Hank** [comment]
Хахахахах, как либерду порвало, что он аж в 2 раза больше текста написал, начал за слова цепляться и правописание, лишь бы обдристаться куда-нибудь по поводу своей политической позиции))

**Comment by Tranberry** [comment]
Can we just remove this "issue".

**Comment by AriaMoradi** [comment]
I'm closing this issue for not being in English, also the launcher not using the russian flag is a political problem that shouldn't have happened in the first place, PRs to changing it are welcome.

@qrrk @NeedFI where did you get the flag icon files from?

**Comment by qrrk** [comment]
@AriaMoradi  we will need to talk on this matter privately.

**Comment by AriaMoradi** [comment]
>  we will need to talk on this matter privately.

I messaged you on discord.
