### ISSUE TITLE
Game error handling

### ISSUE THREAD

**Issue by sadSader** [qrrk/Catapult#145]
OS: OpenSuse 

Some libraries were missing on my system (libSDL2_mixer, libSDL2_ttf) and 
when I pressed "Play" there is no sign of error. I have to manually start cataclysm-tiles to see the error 

If game failed to start stderr should be copied to log.

**Comment by VladicusMagnus** [comment]
For SDL, this is the norm, by the way. An extremely moronic system.

**Comment by coolmanabdul** [comment]
I have same issue, Though I use Linux Mint the game does not start up.

**Comment by AriaMoradi** [comment]
Follow https://github.com/qrrk/Catapult?tab=readme-ov-file#installation if there are further issues, open a new one.
