### ISSUE TITLE
Catapult no longer downloads new releases for BN

### ISSUE THREAD

**Issue by RedPine91** [qrrk/Catapult#146]
![Screenshot 2024-03-04 001338](https://github.com/qrrk/Catapult/assets/30212969/d32b220b-be5e-46aa-8426-92c6db2e8d8e)
The latest Catapult launcher is no longer able to download new releases of BN.  New releases stopped being downloaded as of the 27 Feb 2024 build of BN.  This has coincided with my firewall triggering whenever BN crashes due to Catapult apparently trying to edit the windows crash logs in the WER files.

**Comment by RedPine91** [comment]
This issue might be on BN's end.  I don't see a windows x64 build since feb 27th.

https://github.com/cataclysmbnteam/Cataclysm-BN/releases?q=prerelease%3Atrue&expanded=true

**Comment by RedPine91** [comment]
Issue resolved on BN's end, it was a compiler issue of some sort.

**Comment by VladicusMagnus** [comment]
@RedPine91 О!!! Thanks! )))
