### ISSUE TITLE
[BUG] [24.05a] Experimental releases fetching on Ubuntu can't be performed

### ISSUE THREAD

**Issue by NazarYermolenko** [qrrk/Catapult#160]
While refreshing Experimental releases, I can see only:
Fetching releases for DDA Experimental... and nothing happens....

The Available builds dropdown became active but no option exists
No messages in the terminal with --verbose option

My OS:
Description:	Ubuntu 22.04.4 LTS
Release:	22.04
Codename:	jammy

Launcher Screenshot (can't catch opened dropdown):
![image](https://github.com/qrrk/Catapult/assets/45688056/7370e888-bfc0-49d0-bb4c-0390191824c7)

**Comment by AriaMoradi** [comment]
Try the same with a different ineternet connection or a VPN. I suspect that github is blocking your fetch requests.

**Comment by vvasyliev** [comment]
CDDA experimental linux builds are broken.
https://github.com/qrrk/Catapult/issues/159
https://github.com/CleverRaven/Cataclysm-DDA/issues/74858

**Comment by AriaMoradi** [comment]
closing in favor of #159
