### ISSUE TITLE
Bright Nights has changed its executable name to cataclysm-bn

### ISSUE THREAD

**Issue by scarf005** [qrrk/Catapult#163]
[Due to the changes in BN](https://github.com/cataclysmbnteam/Cataclysm-BN/pull/4989), catapult will be unable to find BN executables since release 2024-07-15. Following is the list of changes.

| OS/variant  | before (releases till 2024-07-14) | after (releases since 2024-07-15) |
| ----------- | --------------------------------- | --------------------------------- |
| UNIX/Curses | cataclysm                         | cataclysm-bn                      |
| UNIX/Tiles  | cataclysm-tiles                   | cataclysm-bn-tiles                |
| Windows     | cataclysm-tiles.exe               | cataclysm-bn-tiles.exe            |

adding a conditional check will likely solve the issue.
thanks for your time.

**Comment by AriaMoradi** [comment]
Fixed in #165
