### ISSUE TITLE
Backups are not working on Linux

### ISSUE THREAD

**Issue by ingles98** [qrrk/Catapult#168]
Using the official AUR package `catapult-bin`.

Creating a backup generates the following error:

```
ERROR: Archive zip command exited with an error (exit code: 127)
   at: call (modules/gdscript/gdscript_functions.cpp:775)
```

**Comment by Zrashin** [comment]
I am also getting this error as well, also running on linux WSL2.

**Comment by Zrashin** [comment]
Alright seems like the issue is that it requires the zip/unzip package installed. Thats what fixed it for me:
for Debian: '''sudo apt install zip'''

I did have gunzip available, but I'm unsure if that would have worked or not, but zip doesn't come default on a lot of distributions.

**Comment by ingles98** [comment]
> Alright seems like the issue is that it requires the zip/unzip package installed. Thats what fixed it for me: for Debian: `sudo apt install zip`
> 
> I did have gunzip available, but I'm unsure if that would have worked or not, but zip doesn't come default on a lot of distributions.

Yep that works indeed. Installed the package by the same name on Arch.

Seems odd that the official AUR package doesn't list it as a dependency for this. Eitherway the error could be a bit more specific like what command was it trying to run since that will let anyone know exactly what Catapult is trying to do. I wouldn't happen to try ZIP since there's yet so many other compression packages and so far i havent ever had the need for this one specifically so it goes unnoticed at least for me.

I wont close it for now and let the bot do its thing just in case someone wants to work on improving on what I listed. I would if i had the time but currently i cant even really even play CDDA.
