### ISSUE TITLE
launcher cannot launch bright nights, looking for wrong exe

### ISSUE THREAD

**Issue by PaganDesparu** [qrrk/Catapult#173]
When trying to launch Bright Nights from Catapault, using the "Play" button, I get the error message "Windows cannot find 
catacalysm-tiles.exe' Make sure you typed the name correctly, then try again.

The exe for BN is catacalysm-bn-tiles.exe

Is there a way to change the filename attempting to launch through catapault?

**Comment by AriaMoradi** [comment]
Upgrade your catapult to [24.07a](https://github.com/qrrk/Catapult/releases/tag/24.07a).

**Comment by PaganDesparu** [comment]
Yup, that did it, thanks!
