### ISSUE TITLE
Kenan modpack will not be updated anymore and new fork is available, will it be reflected in catapult?

### ISSUE THREAD

**Issue by puyebu** [qrrk/Catapult#174]
https://github.com/Zlorthishen/BrightNights-Structured-Kenan-Modpack

**Comment by AriaMoradi** [comment]
I asked Zlor directly and they confirmed that Catapult could start shipping it for BN.

There is no fork of Kenan modpack for DDA as of yet.

**Comment by AriaMoradi** [comment]
fixed in #181
