### ISSUE TITLE
Painting of OMON's prisoner truck instead of the Russian flag?

### ISSUE THREAD

**Issue by girudik** [qrrk/Catapult#175]
![image](https://github.com/user-attachments/assets/103c01a7-ef78-4bf4-be02-77c301833be2)
What the hell is this? Have you completely lost your mind that you put another twitter force instead of the Russian flag?
Let's go further, and put some forces from other places like reddit or maybe... 4chan?
Yeah, github is really a place for shitty activism.

Inb4: 
Not all Russians support the current course of the government. You know it very well. How much effort it takes for the authorities to prove otherwise. And stating otherwise you are echoing the state propaganda that portrays all dissenters as enemies of the motherland. Those who accuse the entire Russian people of all possible sins and personally wishing everything bad for the country.
But no one has done more evil for Russia than its (relatively recent) government.
Don't volunteer to help to spin cycle of the violence.  Russian people have no need to be humiliated by their flag. Humiliation is not an alternative. You don't get the truth by humiliation.  

I say that again, but it's better not to impose your political views through open source.
I am not ashamed of my motherland.
I believe in and love my tricolour. I hope that one day ours will become the flag of the freest country.

*Your dear user from Moscow.

**Comment by AriaMoradi** [comment]
This has been discussed previously, the owner of the repo intends to keep this as is, please contact them privately.
