### ISSUE TITLE
[Bug] Not getting new releases on experimental versions of CDDA

### ISSUE THREAD

**Issue by Lichylite** [qrrk/Catapult#176]
I ran into an issue when running Catapult on arch linux, when trying to download the latest experimental versions at first it only showed me 2 I could download, I rebooted my laptop, and re-installed catapult only for it to show me only 2 versions. This was last night, now I dont have any experimental versions to choose from.
![2024-09-12_14-48](https://github.com/user-attachments/assets/d54e0e3f-e5ff-40f9-9c89-9d1570431dc8)
![imagecata](https://github.com/user-attachments/assets/077e194d-101b-4c2e-a81d-00acf6e12126)
![imagecata2](https://github.com/user-attachments/assets/7d61255a-1cd6-47ec-88db-dafb7423bde7)

**Comment by ISuckM8** [comment]
Unfortunately there's nothing that can be done about this as it depends entirely on whether the main CDDA repo created a linux build or not.

**Comment by AriaMoradi** [comment]
Is CDDA still having broken linux builds?
