### ISSUE TITLE
Latest Expermental Versions Not Populating - CDDA Devs Changed Zip File Naming Convention.

### ISSUE THREAD

**Issue by 0xToast** [qrrk/Catapult#180]
I noticed this problem this evening. 

I am currently on  CDDA Experimental build 2024-11-15-0512, I see the latest version is currently 2024-11-15-2006.

When I ran the refresh, even though I have set it to list 10 releases, I noticed it only brings back 5 releases. After investigating a bit I see that devs have changed the naming conventions on the game files which is causing the catapult launcher to not load the latest builds from release 2024-11-15-0512.

Before: 
![image](https://github.com/user-attachments/assets/d6d0ef24-1667-4336-b5cd-78cc8235e937)

After:
![image](https://github.com/user-attachments/assets/41be96f3-4abf-46b0-ad4a-61b35789fbbb)

**Temporary fix for the folks who still want to use the Catapult launcher in the mean while:**

1. Download the latest version off CDDA and extract within /dda/ folder
![image](https://github.com/user-attachments/assets/4adf1f53-6591-4980-8964-c9622c1adc19)
3. Name it whatever to you prefer (I just call it game1, game2 or game3 etc.)
4. Go back into the folder of the latest version you extracted and create a text file called "catapult_install_info.json"
5. Edit this .json file to reflect the latest experimental version that you just downloded like below (Doesn't really matter what you call it but I stick to the version naming convention):
![image](https://github.com/user-attachments/assets/1cf6d81f-560b-4936-bdb7-52f56d647229) 
6. Save the .json file 
7. Go back to the main folder where your Catapult launcher is installed and edit "catapult_settings.json" to the version you installed, like below (not sure if is necessary but I do it anyway):
![image](https://github.com/user-attachments/assets/257a564e-0639-496f-8982-f863c8faeef1)
8. Relaunch Catapult, you should see the latest version like below:
![image](https://github.com/user-attachments/assets/ab0f027e-f385-4806-8fdf-53e4b16c4e90)
9. Commence the zombie slaying

**Comment by AriaMoradi** [comment]
related https://github.com/CleverRaven/Cataclysm-DDA/pull/77604

**Comment by Pavelgon4ik** [comment]
Appreciate this man. Although I managed to fix this issue by myself, but I was still wondering why experimental versions ducked up, and I got my answer. I wish you devs of Catapult (and CDDA of course) a nice days, because thanks to you people enjoy their time.
