### ISSUE TITLE
[Suggestion] Add Rogue Font as an option for CDDA

### ISSUE THREAD

**Issue by 321nick** [qrrk/Catapult#21]
Really nice, small, 10x10 square font. back when tilesets always had some missing tiles, i used too use this over the default font because it would mean the world wasnt distorted with rectangular fonts. now i still use it for a nice compact interface, so having it added as a font option would be really cool. 

heres the .ttf file:
[rogue.zip](https://github.com/qrrk/Catapult/files/7740732/rogue.zip)

and the fonts.json file that makes it show up properly ingame:
[fonts.zip](https://github.com/qrrk/Catapult/files/7740733/fonts.zip)

**Comment by qrrk** [comment]
Hi. What kind of license does this font have?
Also, could you share a screenshot of how it looks in-game?

**Comment by 321nick** [comment]
> Hi. What kind of license does this font have? Also, could you share a screenshot of how it looks in-game?

AFAIK i found it on the old, now i think gone forever (or atleast, i cant find it) forums, in some thread. i dont think anyone knows who made it or who owns it today anymore.

ingame it looks like this: 
![image](https://user-images.githubusercontent.com/19196462/146907939-6ffb97a5-4c75-49e0-88fe-b13ca3073a8d.png)

**Comment by qrrk** [comment]
TODO:
- [ ] Research the font and try to find out its license.

**Comment by 321nick** [comment]
> TODO:
> 
> * [ ]  Research the font and try to find out its license.


found some stuff, turns out the old forum got ported over too the new forum. 

heres where i asked about it and where i originally got it:

https://discourse.cataclysmdda.org/t/bringing-back-rogue10x10-font/10607

and person who orginally made it (this might not be THE font but its similar and he said he posted the original as open source license): http://www.bay12forums.com/smf/index.php?topic=144897.0

quote: 
"Rogue Yun has a CC0 license so its open for whatever. I think I forgot to add that to the description in the last ttf I uploaded."

**Comment by qrrk** [comment]
Oh, so it is _that_ font. I didn't recognize it. Haven't played DF in a while.

CC0 license is great, but this font doesn't have Cyrillic characters, and that is a major problem. I've set a rule for myself to only add fonts that have Cyrillic letters, since quite a few people play the game in Russian.

That, combined with the fact that it is kind of a specialized font (square fonts don't look great for UI, which is what people mostly customize fonts for), makes it a poor candidate. Sorry, I'm gonna have to say no to this one. Thanks for your effort.

**Comment by Inglonias** [comment]
If you like the font, there's nothing stopping you from putting it into the font folder (not the data/font folder, that will be deleted on updates) and setting up your config/fonts.json file to use it.
