### ISSUE TITLE
Add Frank-3 too launcher

### ISSUE THREAD

**Issue by 321nick** [qrrk/Catapult#26]
The launcher only shows Frank, Frank-1, and Frank 2, but not the (month old as of now) Frank-3 stable version.
here is the options i have:
![image](https://user-images.githubusercontent.com/19196462/147388225-92067d51-0e27-4a5c-8238-0dd3394cc80e.png)

here is the stable version i want:
https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/0.F-3

**Comment by Inglonias** [comment]
Added yesterday. https://github.com/qrrk/Catapult/pull/25
