### ISSUE TITLE
 [Suggestion] View commit summary of available builds.

### ISSUE THREAD

**Issue by c0bnut** [qrrk/Catapult#31]
Upon launching the application or refreshing the list of available builds the summary of all the commits for these builds could be downloaded. There could also be a button you press to open a window displaying the commit summary for the currently selected build.

**Comment by Inglonias** [comment]
If you click the "View Changelog" link in the launcher, it opens a window that displays merged pull requests by date, along with links to them.

![image](https://user-images.githubusercontent.com/2125926/152647093-8657f98c-dc9f-4d5f-85fb-2a918f00e150.png)

**Comment by c0bnut** [comment]
That's exactly what I was looking for thank you. Could I suggest moving the link to a more obvious place like near the build selection?

**Comment by qrrk** [comment]
It was originally supposed to be somewhere near the Update button, but I found it was disproportionately prominent there and decided to move it to the game description. Now that I think about it, people may keep this description hidden, and they'd have to turn it on to see the link, so maybe it should be moved back to the Game tab. I'm thinking somewhere towards the top, like across from stable/experimental selection.

- [ ] Find better place for the changelog link
