### ISSUE TITLE
Tileset migration caused JSON errors

### ISSUE THREAD

**Issue by Inglonias** [qrrk/Catapult#36]
This isn't a bug, really. More an oversight that I thought you might want to be aware of. The fact that tilesets are migrated is ultimately what caused a [minor JSON error](https://github.com/CleverRaven/Cataclysm-DDA/issues/55536) in my game install. I want to suggest that tileset migration be turned off by default, but I don't know how good an idea that is. Regardless, I am bringing this issue to your attention for your thoughts on the matter.

**Comment by qrrk** [comment]
I knew this would be a problem eventually. All the more reason to take another look at #8.
I guess, as a quick solution, we can copy tileset folders one by one into the new game version, and skip the ones that already exist there, so only custom ones added by the user will be copied.

**Comment by qrrk** [comment]
Becomes irrelevant after separating user data from game data.
