### ISSUE TITLE
Problem migrating fonts and sound

### ISSUE THREAD

**Issue by flexoo** [qrrk/Catapult#4]
No matter what I try, it seems it doesn't want to copy over my fonts and sounds. Now I'm unsure if I'm doing something wrong or something's borked.
I have ticked all the things to migrate in settings, but after update to latest experimental those two folders have only the basic files, although the log states the files are copied over.

If you need more infos, let me know.

**Comment by qrrk** [comment]
> after update to latest experimental those two folders _have only the basic files_

This part makes me suspect that you are used to keeping custom soundpacks and fonts in `data/sound/` and `data/font/`. Catapult tries not to mess with contents of `data/`, so it just uses `sound/` and `font/` in the game root instead. Those start out completely empty.

Here's my font setup as an example (old install done without a launcher):

![image](https://user-images.githubusercontent.com/19731636/133099355-50de875d-bff0-474a-a337-765f16e79713.png)

**Comment by flexoo** [comment]
Aah, I missed to adjust the fonts.json. Also, yes, I kept them in data/sound and data/font. After trasfering the files over, everything works like a charm!
Thanks for bumping me in the right direction and a big thanks for this wonderful launcher.

Cheers
