### ISSUE TITLE
Simplified Chinese Translation

### ISSUE THREAD

**Issue by dyxxzgc** [qrrk/Catapult#41]
Glad to see Catapult supporting new languages since 22.02b.
I've done Simplified Chinese translation by myself, by editing `font_info.csv`, `text.csv` and `tips.csv`.
Forgive me, I've never had any experience contributing to a Github project.

My questions are:
1. Are these 3 files the all I need to edit?
2. Should I start a pull request?
3. Could someone help me check if I did everything right?

Sincerely thanks.
[font_info.csv](https://github.com/qrrk/Catapult/files/8196742/font_info.csv)
[text.csv](https://github.com/qrrk/Catapult/files/8196740/text.csv)
[tips.csv](https://github.com/qrrk/Catapult/files/8196741/tips.csv)

**Comment by qrrk** [comment]
This is great news, thank you for your work!

> Are these 3 files the all I need to edit?

Yes.

> Should I start a pull request?

Yes, that would be best. You'll have to fork my repository, clone it, put your .csv file into the project and then commit them.

> Could someone help me check if I did everything right?

I can, if you create a PR. Let's get it going and then see where to go from there.
