### ISSUE TITLE
Bug/troubleshooting. can't download any versions of the game! 

### ISSUE THREAD

**Issue by Ninawindia** [qrrk/Catapult#47]
[00:47:39.115] Downloading cbn-windows-tiles-x64-msvc-untranslated-2022-03-16-0041.zip…
[00:47:39.474] [debug] HTTPRequest info:
Result: 9
Response code: 200
Headers: [Connection: keep-alive, Content-Length: 54350930, Content-Type: application/octet-stream, Content-MD5: j0DiEB0kuCAlgUyxRhvcUA==, Last-Modified: Wed, 16 Mar 2022 01:02:00 GMT, ETag: "0x8DA06E89359DAB8", Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0, x-ms-request-id: 7b0af108-c01e-0059-1ff9-38a5e6000000, x-ms-version: 2020-04-08, x-ms-creation-time: Wed, 16 Mar 2022 01:02:00 GMT, x-ms-lease-status: unlocked, x-ms-lease-state: available, x-ms-blob-type: BlockBlob, Content-Disposition: attachment; filename=cbn-windows-tiles-x64-msvc-untranslated-2022-03-16-0041.zip, x-ms-server-encrypted: true, Fastly-Restarts: 1, Accept-Ranges: bytes, Age: 136, Date: Wed, 16 Mar 2022 05:47:38 GMT, Via: 1.1 varnish, X-Served-By: cache-chi-kigq8000143-CHI, X-Cache: HIT, X-Cache-Hits: 0, X-Timer: S1647409659.594983,VS0,VE38]
[00:47:39.474] [error ] Failed to download cbn-windows-tiles-x64-msvc-untranslated-2022-03-16-0041.zip.

This is the error I get, using debug to see what it might be, whenever I try to download, and I'm not a big good at code mumbo jumbo so any help getting this working would be great!

**Comment by qrrk** [comment]
Here's what I found on result 9:

> ● RESULT_DOWNLOAD_FILE_CANT_OPEN = 9
> HTTPRequest couldn't open the download file.

I think this means it can't create the file it's downloading. Do you have write permission in that folder?
Also, just in case, can you post what folder the launcher is in on your system? You can redact parts of it like your user name.

**Comment by Ninawindia** [comment]
![help](https://user-images.githubusercontent.com/101693137/158708086-c8ff4b81-611e-4188-908e-dd1123a1525c.png)

Here! is this the right way to... show it off? >_>

**Comment by qrrk** [comment]
Yes, thank you, this is all I wanted to see. But I don't notice any problem here. Based on this, everything should work. It even managed to create some files next to itself already, so we know access rights are not an issue. I just re-tested this release of Catapult on windows, with this exact game build, and it works.

The only other thing that comes to mind is some sort of protection in Windows, like Windows Defender, being overly aggressive and preventing the download. Maybe it's something new in Windows 11. I haven't looked at it closely yet.

I assume the same thing happens when you try to install DDA?

**Comment by Ninawindia** [comment]
Indeed! Hmm, maybe windows defender being sucky, it already warned me when I tried to download it. so what could I do about such things? I'd really love to get back into the game!

**Comment by Ninawindia** [comment]
Update! ... it was the Heccin defender, and after disabling it, I was able to download, thanks for the help, I guess it really was just being.. overly aggressive... :|
