### ISSUE TITLE
Connecting controller with launcher open results in opening endless copies of CDDA.

### ISSUE THREAD

**Issue by Drew4484** [qrrk/Catapult#48]
With the launcher running in the background I connect a wired controller. The controller does not have any macros and the launcher is not the active window. It will open as many copies of CDDA as possible. Last test launched 323 copies of CDDA in approximately 15 minutes.

Controller used is a Nintendo Switch Pro via USB. 

System information:
Processor	Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz   4.20 GHz
Installed RAM	32.0 GB
System type	64-bit operating system, x64-based processor

OS information:
Edition	Windows 10 Pro
Version	21H2
Installed on	‎6/‎20/‎2020
OS build	19044.1586
Experience	Windows Feature Experience Pack 120.2212.4170.0

Please let me know what other information you need if you aren't able to replicate/identify this issue.

**Comment by qrrk** [comment]
Catapult still has Godot's default input map, which was never changed. It allows navigating the app with the keyboard, TUI style. It also has mappings for controller actions. Here's how they look:

<img src="https://user-images.githubusercontent.com/19731636/158686740-6e9b6df4-eb4e-4e22-82de-56a11a758f27.png" height=500>

I guess what you describe is possible if the Play button was in focus and a certain action got stuck when the controller was connected. I tried it with an Xbox-compatible controller, but did not see this issue.

Regardless of the exact mechanism of this problem, I think it will help if I just remove all controller actions from the input map. There is no reason for them to be there.

**Comment by qrrk** [comment]
@Drew4484
If this problem persists for you after the next update, please re-open this issue.
