### ISSUE TITLE
22.03c - Save game directory incorrect

### ISSUE THREAD

**Issue by c0bnut** [qrrk/Catapult#50]
In the new release 22.03c, the intervention instructions suggest moving save games from current/save to userdata/save however when launching the game it doesn't recognise the save. Additionally after launching, it creates a range of subfolders such as userdataconfig, userdatafont, userdatagfx etc. when moving the save game files from userdata/save to userdatasave/ the game recognises the files.

![image](https://user-images.githubusercontent.com/36831111/159802149-09429da6-f033-43df-b67c-e10c6cb81461.png)

**Comment by qrrk** [comment]
Oh crap, I think I've seen this kind of problem before with path formation. Stay tuned, I'll check it real quick.

**Comment by qrrk** [comment]
I've figured it out. Looks like Cataclysm always assumes there is a `/` at the end of `--userdir` path, so you have to add one yourself. 

I had done it for Linux, but forgotten for Windows. I've fixed it now and updated the same 22.03c release.

@c0bnut If you have a minute, please re-download and verify.

**Comment by c0bnut** [comment]
All fixed now, thanks for the quick response!
