### ISSUE TITLE
Updating included tilesets

### ISSUE THREAD

**Issue by ggttttggggtt** [qrrk/Catapult#54]
It looks like the tilesets included with the game aren't updated by the launcher, I had to delete the GFX folder to get newer tiles added in Ultica.

**Comment by qrrk** [comment]
Are you using the latest version, of the launcher `22.03c`? This could be a problem with earlier versions, but now it is no longer possible, since the entire game folder is replaced when updating.

**Comment by ggttttggggtt** [comment]
My bad, I was using an old version.
