### ISSUE TITLE
Can't run game

### ISSUE THREAD

**Issue by VagaB00m** [qrrk/Catapult#62]
Hi, I just installed this launcher. I haven't played in a while.

I wanted to start a new run, so I tried to create a new character, but whenever I try it I get this error and doesn't allow me to do anything.

 DEBUG    : Invalid mod_type x

 FUNCTION : string_to_modtype
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\character_modifier.cpp
 LINE     : 65
 VERSION  : 40392e5

Idk if I'm messed up with some files

**Comment by qrrk** [comment]
Looks like a bug in the game itself. A lot of character modifiers in the JSONs have the type `x` (lowercase), but in the current game code an uppercase `X` is expected.

I suggest you report this at [Cataclysm-DDA](https://github.com/CleverRaven/Cataclysm-DDA). Feel free to refer to my comment.

![image](https://user-images.githubusercontent.com/19731636/164939554-8cb04993-4d1a-4ad3-be90-6abe1b530fbc.png)

![image](https://user-images.githubusercontent.com/19731636/164938802-909ec9ae-f1bc-40eb-a255-564551fc6548.png)
