### ISSUE TITLE
Add CO.AG music pack

### ISSUE THREAD

**Issue by remd** [qrrk/Catapult#64]
Before switching to Catapult I used to use the current iteration of the CO.AG music at https://github.com/Fris0uman/CDDA-Music-Packs with @'s soundpack. The opening track CO.AG_Cataclysm.ogg is basically iconic for me now and I miss it.

Since it isn't a soundpack (it'd have to overwrite the music folder of an installed soundpack) I'm not sure if it's a good candidate for Catapult but I thought I'd ask anyway.

Thanks for all your hard work on this project!

**Comment by qrrk** [comment]
It may be worth adding as an additional feature of soundpack management that automatically downloads CO.AG music and extracts in into an installed soundpack.
