### ISSUE TITLE
[Suggestion] Toggle for allowing builds with built in sound

### ISSUE THREAD

**Issue by UnicodeTreason** [qrrk/Catapult#66]
As per https://www.reddit.com/r/Cataclysm_DDA/comments/uih1ob/psa_the_game_now_comes_with_an_actual_soundpack/
The CCDA releases now have an option that contains the official soundpack.
It would be helpful to have a toggle to allow these builds to appear in the build list.

**Comment by qrrk** [comment]
Since this soundpack is also [available](https://github.com/Fris0uman/CDDA-Soundpacks) separately, I think a better solution is just to add it to the Soundpacks tab. No need to complicate the UI further for something that can be achieved without altering it at all.
