### ISSUE TITLE
Ошибка при установке

### ISSUE THREAD

**Issue by gogaster** [qrrk/Catapult#68]
У меня старый пк и интегрированная карта, но катаклизм запускается. При попытке установить лаунчер - выскакивает данная табличка, почините позязя

![1](https://user-images.githubusercontent.com/27226073/168124151-bdf5a579-38c3-4c09-883a-6ba367e1d033.PNG)

**Comment by qrrk** [comment]
Тут, к сожалению, ничего нельзя сделать, нужна поддержка хотя бы OpenGL 2.1.
