### ISSUE TITLE
[Bug] It's possible to switch fork during various operations

### ISSUE THREAD

**Issue by olanti-p** [qrrk/Catapult#7]
UI elements are generally disabled during long operations, but drop-down list for game selection is not.

This allows user to switch game during some long running operations:
* Soundpack download/install (doesn't seem to be causing problems)
* Batch mod installation/removal (causes installation/removal failures)

Additionally, after switching to another fork it's possible to initiate its installation/update, though that seems to instantly fail.

Version: 21.09f

**Comment by qrrk** [comment]
Thanks for noticing this. It was a simple oversight: the list wasn't added to the two groups that get disabled during soundpack and mod operations.
