### ISSUE TITLE
Launcher opens, but no window appears.

### ISSUE THREAD

**Issue by c0712341** [qrrk/Catapult#75]
Running on windows 10, was working yesterday, but stopped working today. Whenever I run the .exe, the application shows up in the taskbar, but the actual window does not exist. I can share more information if told how to do so, I tried running it in debug mode but nothing changed.

**Comment by qrrk** [comment]
Maybe the window is opening off-screen somehow? Try deleting or renaming the config file `catapult_settings.json` to reset the window size and position.

**Comment by c0712341** [comment]
While the window wasn't offscreen, just blank, deleting the config file did work, thanks!
