### ISSUE TITLE
[Suggestion] Separate user data and game data

### ISSUE THREAD

**Issue by olanti-p** [qrrk/Catapult#8]
Both BN and DDA support `--userdir <path>` command line option, which allows to specify base path for user directories (by default same as current path on Windows and Linux).

It can be used to separate user data from installation data, so during update the launcher wouldn't need to touch user directories at all.

**Comment by qrrk** [comment]
Pros:
- Simpler, faster and more reliable update procedure.
- Zero risk of damaging user data during updates.
- Easier creation/restoration of backups (when the time comes to add them).
- Clean separation between preinstalled and user-installed *tilesets* (when they are added).

Cons:
- The user can't choose *not* to carry over certain data when updating.
- Starting the game without the launcher will give unexpected results.

**Comment by Maddremor** [comment]
To provide extra context:

https://github.com/CleverRaven/Cataclysm-DDA/wiki/Command-Line-Parameters#help
