### ISSUE TITLE
how do you move dda to another disk?

### ISSUE THREAD

**Issue by matt32106** [qrrk/Catapult#87]
not an issue, just a question, I don't want to create symbolic links or whatever. How do I move to another disk?

**Comment by qrrk** [comment]
You mean just the game itself, separately from the launcher? I'm afraid that's currently not possible. I'm not even sure symbolic links would work. Why not just move everything together?

**Comment by matt32106** [comment]
i was wondering how to move the dda directory to somewhere else without moving the launcher but did not find a path in th options. Yes, moving everything works, just had to create a link to the launcher on the desktop. Not a big deal.
