### ISSUE TITLE
Bright nights stable channel unselectable

### ISSUE THREAD

**Issue by BlueManedHawk** [qrrk/Catapult#88]
There is no way to select the "stable" channel for Bright Nights.

**Comment by qrrk** [comment]
I've been so busy relocating that I missed when Bright Night actually started making stable releases as they had planned!

**Comment by weakman54** [comment]
What's the status on this? I've been thinking of looking into this myself and doing a PR

**Comment by qrrk** [comment]
That would be great! Right now I am still too busy on my day job and with other things to take care of it myself.

**Comment by weakman54** [comment]
I'm somewhat busy myself, but I'll hopefully be able to take a look tonight
